default_language_version:
  python: python3.10

exclude: ^package.json|package-lock.json/

ci:
  skip: [pyright]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: debug-statements
      - id: fix-encoding-pragma
        args: [--remove]

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8

  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        args:
          - -L
          - hist
          - --skip="*/.*,package.json,package-lock.json

  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        name: autoflake
        args: ["--in-place", "--remove-unused-variables", "--remove-all-unused-imports"]
        language: python
        files: \.py$

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.1
    hooks:
      - id: pyupgrade

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: pyright
        language: node
        types: [python]
        additional_dependencies: ["pyright@1.1.230"]
        pass_filenames: false

  # From https://github.com/pre-commit/mirrors-prettier/blob/master/.pre-commit-hooks.yaml
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        description: ""
        entry: prettier --write --list-different --ignore-unknown
        language: node
        "types": [text]
        args: []
        require_serial: false
        additional_dependencies: ["prettier@2.6.0", "prettier-plugin-tailwindcss@0.1.8"]
        minimum_pre_commit_version: "0"
