default_language_version:
    python: python3.10

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

- repo: https://github.com/psf/black
  rev: 22.1.0
  hooks:
  - id: black

# - repo: local
#   hooks:
#   - id: pyright
#     name: pyright
#     entry: pyright
#     language: node
#     types: [python]
#     additional_dependencies: ['pyright@1.1.230']
