channels:
  - "conda-forge"
dependencies:
  - python=3.10
  - imagecodecs
  - numpy
  - pillow
  - pip
  - pyserial
  - rich
  - setuptools
  - pydantic
  - pyyaml
  - tifffile
  - pip:
      - pyserial-asyncio