channels:
  - "conda-forge"
dependencies:
  - python=3.10
  - numpy
  - pillow
  - pip
  - pyserial
  - pytest
  - returns
  - rich
  - setuptools
  - pydantic
  - tifffile
  - yaml
  - pip:
    - pyserial-asyncio