[build-system]
build-backend = 'setuptools.build_meta'
requires = ["setuptools >= 43.0.0"]

[tool.black]
include = 'pyseq2server'
line-length = 110
target-version = ['py310']

[tool.isort]
known_first_party = ["pyseq2", "pyseq2server"]
line_length = 110
profile = "black"
py_version = 310
src_paths = ["pyseq2server"]

[tool.pyright]
pythonVersion = "3.10"
reportMissingTypeStubs = false
reportUnknownMemberType = false
reportUntypedFunctionDecorator = false
reportUnusedFunction = false
reportUnusedImport = false
reportUnusedVariable = false
reportWildcardImportFromLibrary = false
typeCheckingMode = "strict"

[tool.pytest.ini_options]
asyncio_mode = "auto"
minversion = "7.0"
testpaths = ["tests"]
