[tool.black]
include = 'python'
line-length = 110
target-version = ['py310']

[tool.isort]
known_first_party = ["pyseq2", "pyseq2server"]
line_length = 110
profile = "black"
py_version = 310
src_paths = ["pyseq2server"]

[tool.pyright]
pythonVersion = "3.10"
reportMissingTypeStubs = false
reportUnknownMemberType = false
reportUntypedFunctionDecorator = false
reportUnusedImport = false
reportUnusedVariable = "warning"
reportWildcardImportFromLibrary = false
