site_name: PySeq 2501
repo_url: https://github.com/chaichontat/pyseq2501
repo_name: chaichontat/pyseq2501

theme:
  name: material
  features:
    - navigation.instant
    - toc.integrate
    - navigation.top
docs_dir: .
site_dir: ../site
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/chaichontat/goff-rotation

nav:
  - Home: index.md
  - Architecture: architecture.md
  - HiSeq:
      - Overview: hiseq.md
      - Programs: programs.md
  - Reference: reference.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - abbr
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')
          rendering:
            members_order: source
  - git-revision-date-localized:
      type: iso_datetime
