name: Example Svelte Deployment

on:
  push:
    branches:
      - main
  pull_request:
  release:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "17"
          cache: "npm"

      - run: npm install

      - run: npm run build

      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

  test-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
      max-parallel: 5
    env:
      FAKE_HISEQ: 1

    steps:
      - uses: actions/checkout@v2

      - name: Cache conda
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('.github/ci_env.yml') }}

      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: latest
          environment-file: environment.yml
          activate-environment: pyseq
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!

      - name: Install with Poetry
        run: |
          poetry install

      - name: Test with Pytest
        run: |
          pytest -rP

  test-tox:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
      max-parallel: 5
    env:
      FAKE_HISEQ: 1

    steps:
      - uses: actions/checkout@v2

      - name: Cache conda
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('.github/ci_env.yml') }}

      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: latest
          environment-file: .github/ci_env.yml
          activate-environment: pyseq
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!

      - name: Test with Tox
        run: |
          tox -vv
