name: Python Package using Conda

on:
  push:
    paths:
      - .github/**
      - scripts/**
      - src/**
      - tests/**
      - docs/**

jobs:
  deploy_docs:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
