name: Conda

on:
  push:
  pull_request:
    branches:
      - main
  release:
  workflow_dispatch:
    inputs:
      reason:
          description: Reason for the workflow dispatch.
          required: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
      max-parallel: 5
    env:
      FAKE_HISEQ: 1

    steps:
      - uses: actions/checkout@v2

      - name: Install Conda environment from environment.yml
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: environment.yml
          environment-name: pyseq
          cache-env: true

      - name: Install with pip
        run: |
          pip install .

      - name: Type check with Pyright
        run: |
          npm i -g pyright
          pyright pyseq2

      - name: Test with Pytest
        run: |
          pip install pytest pytest-cov pytest-asyncio hypothesis
          pytest -rP

      - name: Build docs
        if: ${{ matrix.os == 'ubuntu-latest'}}
        run: |
          mamba install mkdocs mkdocs-material
          pip install mkdocstrings[python] mkdocs-git-revision-date-localized-plugin
          mkdocs build

      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' && matrix.os == 'ubuntu-latest'}}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
